SYSTRAN/faster-whisper

- faster_whisper/vad.py
> Fix VAD index error when a predicted timestamp is too large

- faster_whisper/transcribe.py
This increases compatibility with OpenAI Whisper's [`whisper.load_model()`](https://github.com/openai/whisper/blob/b80bcf610d89960bc658b61af9c333fc6d978d78/whisper/__init__.py#L97) and is useful for downstream integrations
> Expose download location in WhisperModel constructor

- faster_whisper/transcribe.py
It would be great if we can include the transcription_options in AudioInfo.
My application is only making a few changes but leaving the rest as default. However, I would like to record down all settings (including those that I did not specify) so that the audio can be transcribed again identically in future if need be.
> Add transcription_options to AudioInfo

- faster_whisper/transcribe.py
At the moment, the segments returned by faster-whisper are a subtly different shape to those returned by Whisper and also lack some of the information that JSON/verbose transcription results from that repo provide.
It appears that all of the information necessary to return these is in fact present in the transcribe function of faster-whisper, but they're simply not returned at present.
This PR adds those in and adjusts the naming of avg_log_prob to be consistent with Whisper.
The quirk I'm not certain of is whether it would be best to adjust the returned `seek` value on the other side of the VAD, but I don't do that at present.
> Align segment structure with openai/whisper

- faster_whisper/vad.py
- tests/test_transcribe.py
When VAD is applied, this prevents some words to be assigned to the previous speech chunk in the original audio.
> Increase the default value of speech_pad_ms to 400 ms

- faster_whisper/transcribe.py
- tests/test_transcribe.py
This change adds a `all_language_probs` field to `TranscriptionInfo` so that when language detection is done, we can recover the full probabilities from the model in addition to the top one.
> transcribe: return all language probabilities if requested

- faster_whisper/utils.py
> rety model download locally if huggingface throws an http error.

- requirements.txt
onnxruntime 1.15.0 was just released with Python 3.11 support.
> Enable onnxruntime dependency for Python 3.11

- faster_whisper/utils.py
Models converted with CTranslate2 3.16 and above now save the vocabulary as `vocabulary.json`.
For now there is no plan to update the converted models in the Hugging Face Hub which still use vocabularies as text files. But we make this change now in case they get updated in the future.
> Do not specify the vocabulary file extension in the download pattern

- faster_whisper/transcribe.py
Discussion in https://github.com/guillaumekln/faster-whisper/issues/299#issuecomment-1594773275
This pull request allows users to specify an Iterable of token IDs for initial_prompt.
There is a minor deviation from that comment.
Instead of a list as an input, I've allowed `Iterable[int]`.
I think users would probably want to use a rotating array(such as `deque(maxlen=224)`) to automatically drop off old tokens.
Also, both lists and deques are iterable and can be input into the method.
> Allow users to input an Iterable of token ids into initial_prompt

- README.md
- faster_whisper/transcribe.py
- faster_whisper/utils.py
Recently, I successfully converted a fine-tuned Whisper model using CTranslate and utilized it by calling the following code:
```
model = faster_whisper.WhisperModel('converted-whisper-model')
```
, which works well.
However, when I attempted to push this converted model into Hub, I encountered an issue where the `WhisperModel` was unable to directly download the converted model from Hub. To resolve this problem, I made slight modifications to the `download_model` function in order for it to work properly.
> Add support for using whisper models from Huggingface by specifying the model id.

- faster_whisper/transcribe.py
- requirements.txt
- tests/test_transcribe.py
> Prepend prefix tokens with the initial timestamp token

- faster_whisper/transcribe.py
Related to https://github.com/openai/whisper/pull/1377
> Return result with best log prob when all temperature fallbacks failed

- faster_whisper/transcribe.py
Without this line, the next 30-second window will use the same encoder output as the previous one which is incorrect.
> Invalidate the cached encoder output when no_speech threshold is met

- faster_whisper/transcribe.py
CTranslate2 has a `repetition_penalty` argument in its model.generate method. It was however missing from WhisperModel.transcribe
Simply added the `repetition_penalty` argument
As it is, after each generation, the output is filtered if it's too repetitive (based on compression_ratio).
`repetition_penalty` can make it so repetition is penalized during the generation (decoding) itself, making some failure cases like I found disappear.
By "failure" in this case I mean taking 23 seconds to process a 13 second clip (which usually takes ~2.4 seconds) because of obvious repetition in multiple fallbacks, as seen in this image  https://files.catbox.moe/d0psud.png, where each line starting with `needs_fallback` shows the result of a `model.generation`.
`repetition_penalty` solves this hallucination …
> added repetition_penalty to TranscriptionOptions

- faster_whisper/transcribe.py
Simple change that adds the seconds of audio removed by the VAD to the returned info object. This was added next to the duration of the original audio. Silero VAD refers to that as silence so that is the name I used.
> Added audio duration after VAD to TranscriptionInfo object

- faster_whisper/audio.py
> Force the garbage collector to run after decoding the audio with PyAV

- faster_whisper/transcribe.py
This parameter is available in the CTranslate2 API so let's expose it.
> Expose generation parameter `no_repeat_ngram_size`

- faster_whisper/transcribe.py
The encoder must be executed in each loop iteration, except maybe the first one if the encoder output is saved from the language detection.
The previous code was error-prone and required an explicit invalidation of the encoder output.
> Always run the encoder at the beginning of the loop

- README.md
- faster_whisper/tokenizer.py
- faster_whisper/transcribe.py
- faster_whisper/utils.py
- requirements.txt
This is a continuation of  #548 so credit to its contributors and author [@stillmatic](https://github.com/stillmatic).
I've tried to adress some of the comments recieved on that PR.
Potential TODOs:
- Dynamic _LANGUAGE_CODES in tokenizer.py depending on whether V3 (which supports "yue") is loaded.
> Add V3 Support

- faster_whisper/audio.py
The `av.open` functions checks input metadata to determine the mode to open with ("r" or "w"). If an input to `decode_audio` is found to be in write-mode, it will fail. Forcing read mode solves this.
I encountered this in a FastAPI application, where I used the `UploadFile` type to accept a file in my API endpoint. This uses a `SpooledTemporaryFile` underneath. In some circumstances, such as with small input files, this spooled file will have mode "w+b" when we first attempt to read it, causing `decode_audio` to try opening with `av.open` in write mode, and failing. Forcing to read-mode fixes this.
It would not make sense for `av.open` in `decode_audio` to ever use write-mode, so this should not negatively impact any other uses.
> Force read-mode in `av.open`

- faster_whisper/transcribe.py
Fixing: https://github.com/SYSTRAN/faster-whisper/issues/603
Fixes broken prompt_reset_on_temperature functionality.
Broken because `generate_with_fallback()` doesn't return final temperature.
Regression since PR356 -> https://github.com/SYSTRAN/faster-whisper/pull/356
> Fix broken prompt_reset_on_temperature

- faster_whisper/transcribe.py
Fixing: https://github.com/SYSTRAN/faster-whisper/issues/621
Regression since PR: https://github.com/SYSTRAN/faster-whisper/pull/225
**The bug**: It's "silence" when decoding has failed due to `compression_ratio_threshold` [+no_speech_threshold] in https://github.com/SYSTRAN/faster-whisper/pull/225, when further down the code it's not "silence" anymore.
"Silence" should be only when decoding has failed due to `log_prob_threshold`  [+no_speech_threshold].
As described there:
https://github.com/SYSTRAN/faster-whisper/blob/44f7e589478866546bfcd1d105e254a74e2caad5/faster_whisper/transcribe.py#L239-L241
The bug opens the gates for the hallucination loops.
> Bugfix: Illogical "Avoid computing higher temperatures on no_speech"

- requirements.txt
Fix for https://github.com/SYSTRAN/faster-whisper/issues/677 https://github.com/SYSTRAN/faster-whisper/issues/678 https://github.com/SYSTRAN/faster-whisper/issues/571
Bumps up PyAV version to support Python 3.12.x
> Bumps up PyAV version to support Python 3.12.x

- faster_whisper/transcribe.py
- faster_whisper/utils.py
Same with https://github.com/openai/whisper/pull/1838
> Skip silence around hallucinations

- faster_whisper/audio.py
- faster_whisper/transcribe.py
Quick fix for https://github.com/SYSTRAN/faster-whisper/pull/646
I tested with a poor quality audio file (192s) and received:
- `ctranslate2==3.24.0` and `faster-whisper==0.10.1`,  the execution time is 12.9s
- `ctranslate2==3.24.0` and `faster-whisper==1.0.1`,  the execution time is 28.9s
Below is my testing code:
```python
model = WhisperModel('large-v3', device='cuda')
segments, info = model.transcribe(jfk_path, word_timestamps=True)
```
After investigating, I found that the logic changes below increased the latency:
Old logic:
```python
segment = features[:, seek : seek + self.feature_extractor.nb_max_frames]
segment_size = min(
self.feature_extractor.nb_max_frames, content_frames - seek
)
``` 
New update logic in https://github.com/SYSTRAN/faster-whisper/pull/646:
```python …
```
> Update logic to get segment from features before encoding

- README.md
Fix typo. Change `faster-ditil-whisper` to `faster-distil-whisper`
> Fix README.md typo 'ditil'

- faster_whisper/transcribe.py
Same with https://github.com/openai/whisper/pull/676
> Improve language detection

- README.md
- faster_whisper/utils.py
The latest Distil-Whisper model, [distil-large-v3](https://huggingface.co/distil-whisper/distil-large-v3-ct2), is intrinsically designed to work with the OpenAI sequential algorithm.
This PR adds support for this checkpoint.
> Add support for distil-large-v3

- faster_whisper/transcribe.py
Regression since https://github.com/SYSTRAN/faster-whisper/pull/732 PR [Improve language detection]
Bug can happen if VAD didn't found voice in audio.
Bugfix brings back the previous behaviour on empty audio.
> Bugfix: code breaks if audio is empty

- faster_whisper/transcribe.py
Prevent silly things to happen.
> Foolproof: Disable VAD if clip_timestamps is in use

- README.md
Edits to the README regarding installation/CUDA based on discussion on these issues: https://github.com/SYSTRAN/faster-whisper/issues/783 and https://github.com/SYSTRAN/faster-whisper/issues/717
- Updated libraries to install for CUDA 12 (because of latest `ctranslate2` support for only CUDA 12)
- Added note regarding CUDA 11 support.
> CUDA version and updated installation instructions

- requirements.txt
Constraining the version of tokenizers to `<0.16` makes faster-whisper incompatible with the latest version of transformers, and the tests all pass when using the latest version (`0.19.1`).
> Loosen tokenizers version constraint

- faster_whisper/transcribe.py
I think this phrasing is clearer. Also, if you're open to a change in behaviour, I would consider throwing an exception if mutually incompatible options are provided (e.g. `hotwords` and `prefix`). I can add a commit doing this if you're interested.
I've added some other minor doc cleanups as well.
> Clarify documentation for hotwords

- faster_whisper/transcribe.py
Changed the code from updating the TranscriptionOptions class instead of the options object (transcribe.py, lines 493-500), which likely was the cause of the unexpected behaviour of clip_timestamps not updating when calling transcribe multiple times
Original:
```py
TranscriptionOptions.clip_timestamps=[
float(ts)
for ts in (
options.clip_timestamps.split(",")
if options.clip_timestamps
else []
)
]
```
Updated:
```py
options = options._replace(
clip_timestamps=[
float(ts)
for ts in (
options.clip_timestamps.split(",")
if options.clip_timestamps
else []
)
]
)
```
> Fix #839 incorrect clip_timestamps being used in model

- faster_whisper/transcribe.py
- faster_whisper/utils.py
This PR updates the `WhisperModel` `__init__` method and the `download_model` docstrings to include the new distil variants. This enhancement allows code editors to display the available models in their hints
> Add distil models to WhisperModel init and download_model docstrings

- docker/Dockerfile
Installation of `libcudnn8` and `libcudnn8-dev` isn't necessary when using `nvidia/cuda:12.2.2-cudnn8-runtime-ubuntu22.04` as the base image
Build time reduced from 165s to 53s (on g6.4xlarge EC2 instance) 
Final image size reduced from 6.07GB to 4.6GB
> Docker file improvements

- README.md
Hey, I've just created a [faster-whisper-server](https://github.com/fedirz/faster-whisper-server), and I'd like to add it to the list of community integrations. I think it could be useful to some folks that want to work with `faster-whisper` using other programming languages or using an OpenAI SDKs.
> docs: add 'faster-whisper-server' community integration

- faster_whisper/transcribe.py
Using clip_timestamps to improve the initial seek for language detection, avoiding incorrect detection at the start of the audio file.
> Improve language detection when using clip_timestamps

- faster_whisper/tokenizer.py
- faster_whisper/transcribe.py
- tests/test_transcribe.py
This matches the implementation of OpenIA Whisper suppress_tokens with faster-whisper.
In the default behaviour (-1) it filters out the non_speech_tokens which should help to filter out non-relevant text to the transcription.
> Filter out non_speech_tokens in suppressed tokens

- faster_whisper/transcribe.py
- requirements.txt
This PR removes Remove the usage of `transformers.pipeline` from `BatchedInferencePipeline` because there's no need to use it in the first place
this simplifies the code and removes a requirement
it also fixes #919 
it was caused by wrong `num_frames` argument when finding the alignments, it was assumed that inferring it from encoder output size was sufficient but turned out to cause issues such as #919 when the actual segment size is much less that the inferred size
> Remove the usage of `transformers.pipeline` from `BatchedInferencePipeline` and fix word timestamps for batched inference

- faster_whisper/audio.py
- requirements.txt
This PR reverts the torchaudio code that was added in #856 and removes `torchaudio` dependency but still keeps `torch`
the reason why `torch` wasn't removed in this PR is that feature extraction still depends on it and I didn't want to include the numpy feature extraction in this PR to keep it simple and to reduce the number of conflicts to be resolved with #936 
this should be merged before #936, after both are merged, a new PR will be created to completely remove the `torch` dependency
> revert back to using PyAV instead of torch audio

- faster_whisper/audio.py
- faster_whisper/transcribe.py
This adheres faster whisper implementation to the original OpenAI implementation as discussed in #1084 
These are WER comparisons before and after
These figures can be reproduced by running `benchmarks/yt_commons.py` and switching the batched inference to sequential
```python
word_timestamps=False,
without_timestamps=True,
vad_filter=True,
```
| Model               | Before WER | After WER  |
|---------------------|------------|------------|
| distil-large-v3     | 26.277     | **14.762** |
| distil-large-v2     | **71.848** | 81.456    |
| distil-medium.en    | 68.044 | **66.565**     |
| distil-small.en     | 68.719     | **67.220** |
the performance regression of `distil-large-v2` can be ignored because `distil-large-v3` should be used as a drop-in replacement
This should also affect …
> Use correct features padding for encoder input

- faster_whisper/transcribe.py
Fixes suboptimal performance on CPUs with less than 16 cores by setting the number of CPU threads to the actual number of physical cores dynamically.
Fixes https://github.com/SYSTRAN/faster-whisper/issues/917
> Set CPU threads according to the machine

- faster_whisper/transcribe.py
- faster_whisper/vad.py
this is to allow conversion of `Segment` and `Words` to `dict` or `json` without recursively going through them
Similar to #667 and #1104 
Unlike NamedTuples, dataclasses are not iterable, so they need to be converted to a dict first
> replace `NamedTuple` with `dataclass`

- faster_whisper/transcribe.py
the current value of `language_detection_threshold` means that `language_detection_segments` will be 1 regardless of the user set value, the new value will ensure that `language_detection_segments` is respected
> change `language_detection_threshold` default value

- faster_whisper/audio.py
- faster_whisper/feature_extractor.py
- faster_whisper/transcribe.py
- faster_whisper/vad.py
- requirements.txt
- tests/test_transcribe.py
Hi all,
This PR aims to remove the torch dependency as it's only used for feature extraction, there are 2 options:
1. use NumPy only and scrap GPU acceleration completely, this will slightly simplify the FE code by removing the device handling and framework handling code
2. use NumPy + CuPy (the current implementation), this will allow the usage of GPU acceleration for those who want it, we still need to decide whether CuPy will be included in the base requirements or maybe as an optional requirement or none at all
These are performance figures on a 30s segment using [this](https://gist.github.com/MahmoudAshraf97/87a96999cd29efb3b6b13591b89cd1ea) script
```bash
OMP_NUM_THREADS=4 OPENBLAS_NUM_THREADS=4 MKL_NUM_THREADS=4 VECLIB_MAXIMUM_THREADS=4 NUMEXPR_NUM_THREADS=4 taskset -c 0-3 python …
```
> Remove `torch` dependency, Faster numpy Feature extraction

- faster_whisper/transcribe.py
this fix #1140 
code from commit before #856 <https://github.com/SYSTRAN/faster-whisper/blob/fbcf58bf984a309edab9d21e23bca872e1d5fe61/faster_whisper/transcribe.py#L1051-L1055>
> fix: Use correct `seek` value in output, fix word timestamps when the initial timestamp is not zero

- README.md
- faster_whisper/transcribe.py
- tests/test_transcribe.py
This PR aims to unify language detection in both `WhisperModel` and `BatchedInferencePipeline`
Summary:
* Supported new options for batched transcriptions:
* `language_detection_threshold`
* `language_detection_segments`
* Updated `WhisperModel.detect_language` function to include the improved language detection from #732  and added docstrings, it's now used inside `transcribe` function.
* Removed the following functions as they are no longer needed:
* `WhisperModel.detect_language_multi_segment` and its test
* `BatchedInferencePipeline.get_language_and_tokenizer`
* Added tests for empty audios
> Deduplication of language detection functions

- faster_whisper/transcribe.py
This PR aims to further refine `BatchedInferencePipeline` class to include more transcription options and other improvements
Summary:
* Supported new options for batched transcriptions:
* `temperature`
* `hotwords`
* fixed initial prompt
* moved `generate_segment_batched` function from `WhisperModel` to `BatchedInferencePipeline`
* make the pipeline class stateless
* clarified documentation about what arguments do not have an effect in batched transcription
> Cleanup of `BatchedInferencePipeline`

- faster_whisper/transcribe.py
> Fix `list index out of range` in word timestamps

- benchmark/evaluate_yt_commons.py
- benchmark/requirements.benchmark.txt
- benchmark/wer_benchmark.py
This replaces `evaluate` with `jiwer` and removes pytorch from YT Commons evaluation
TODO: handle missing links in YT Commons evaluation
> use `jiwer` instead of `evaluate` in benchmarks

- faster_whisper/transcribe.py
I'm seeking closer adherence to the original OpenAI Whisper implementation and hence removing this after it's introduction in #856, it might have some use cases but I'd prefer to add it later if needed after this release
I also removed `WhisperModel.device` attribute because it didn't return the actual device value, the correct value can be found at `WhisperModel.model.device`
> remove `log_prob_low_threshold`

- faster_whisper/vad.py
For no reason in v1.1.0 VAD parameter `threshold` was changed to `onset`  and `neg_threshold` to `offset`. 
This PR brings original naming back.
> Brings back original VAD parameters naming

- faster_whisper/transcribe.py
Make batched suppress_tokens behaviour same as in sequential mode.
> Make batched suppress_tokens behaviour same as in sequential

- faster_whisper/vad.py
fixes #1193 and #1169 
VAD implementation consumes humongous memory amount [original Silero doesn't have this problem]
This PR should fix the OOM problem.
Alt solution could be removing `lru_cache`.
> Fixes OOM Errors - too high RAM usage by VAD

- faster_whisper/vad.py
Fix neg_threshold.
Now it should work properly, before its default was hardcoded to 0.35
> Fix neg_threshold

- README.md
Was previously named faster-whisper-server. They've decided to change the name from faster-whisper-server to speaches, as the project has evolved to support more than just ASR: https://github.com/speaches-ai/speaches
> Update README.md with speaches instead of faster-whisper-server

- faster_whisper/transcribe.py
- faster_whisper/utils.py
These changes let users load private or gated HuggingFace models.
- WhisperModel.__init__(...):
- accepts `use_auth_token` and passes it to download_model
- download_model(...):
- new optional `use_auth_token` kwarg
- uses token in`huggingface_hub.snapshot_download`
> Feature: Allow loading of private HF models

- faster_whisper/transcribe.py
- faster_whisper/vad.py
if a number already exists in a list and the index is `i`, `bisect` returns `i+1` index where it should be returning `i` which results in the timestamp assigned to the next vad segment
> bugfix: Get correct chunk index when restoring timestamps

- faster_whisper/transcribe.py
- faster_whisper/vad.py
- tests/test_transcribe.py
The current VAD implementation in batched transcription is only used for segmentation, silence is only removed at segments boundaries, for example, if we have a speech segment from 1 to 3 and another from 9 to 10, the resulting segment will be from 1 to 10, including a large silence period from 3 to 9 which is prone to hallucinations
This PR concatenates speech only until the desirable chunk size is reached and ignoring the silence in-between thus reducing hallucinations in batched mode
Since the speech is condensed, more words per segment should be expected in the transcript, potential slight speedup is also expected due to less segments for long files
Results after increasing `min_silence_duration_ms` to 800:
| Model               | Before WER | After WER  | …
> Remove Silence in Batched transcription
