SYSTRAN/faster-whisper

faster_whisper/transcribe.py

Add the initial_prompt parameter

---

faster_whisper/transcribe.py

Expose the device_index argument

---

faster_whisper/transcribe.py

Accept the audio waveform as an input to transcribe()

---

README.md
faster_whisper/tokenizer.py
faster_whisper/transcribe.py
requirements.txt

Add word-level timestamps

---

faster_whisper/audio.py

Ignore the invalid audio frames

---

faster_whisper/transcribe.py
faster_whisper/utils.py

Add some info and debug logs

---

faster_whisper/transcribe.py

Keep segment timestamps aligned with words timestamps after VAD

---

.gitignore

Changes on `.gitignore` to exclude cache, editor files, and other non-essential files from the repository.

Configure git ignore for more files.

---

README.md

Clarify that the returned segments value is a generator

---

faster_whisper/transcribe.py
faster_whisper/utils.py

Allow specifying local_files_only to prevent checking the Internet everytime

---

faster_whisper/transcribe.py

Fixes #138 
I believe this is correct, I wanted to test it so I implemented a PR for it

Fix where tokens are reset

---

faster_whisper/transcribe.py
faster_whisper/utils.py
tests/test_utils.py

See https://github.com/guillaumekln/faster-whisper/issues/181

Use cache_dir instead of local_dir

---

MANIFEST.in

Include requirements files in sdist

---

faster_whisper/__init__.py
faster_whisper/version.py
setup.py

Export __version__ at the module level

---

README.md

This contribution aims to bring faster-whisper users to explore community contributions that are fully scalable and production-ready. This is a piece of work that has already been implemented in several use cases and open sourcing the code means that anyone can quickly make the most of our joint efforts :)

Update README with community repo using FW

---

faster_whisper/transcribe.py

Port commit https://github.com/openai/whisper/commit/255887f219e6b632bc1a6aac1caf28eecfca1bac

Squash long words at window and sentence boundaries

---

faster_whisper/transcribe.py

Port commit https://github.com/openai/whisper/commit/e334ff141d5444fbf6904edaaf408e5b0b416fe8

Avoid computing higher temperatures on no_speech segments

---

faster_whisper/transcribe.py

Both `median_duration` and `max_duration` have already been calculated on lines 719-720.

Remove duplicate code

---

faster_whisper/transcribe.py

Produce DEBUG log message if prompt_reset_on_temperature threshold is met.

Adds DEBUG log message for prompt_reset_on_temperature

---

README.md

Hi @guillaumekln , I worked on a small tool for a local non-profit and used faster-whisper for the transcription needed for archiving purposes. The tool and the editor, both are open source so sharing it in the docs. 
Short description:
wscribe is a utility to generate transcript specifically to make it easy for further manual edits accompanied by the wscribe-editor
- https://github.com/geekodour/wscribe
- https://github.com/geekodour/wscribe-editor

docs: add wscribe to community integrations

---

faster_whisper/transcribe.py

Same with [openai/whisper#1559](https://github.com/openai/whisper/pull/1559)

Word timing tweaks

---

README.md

Added aTrain GUI faster-whisper transcription and diarization tool as community project.

Add GUI faster-whisper project README.md

---

README.md

Whisper-Streaming mention

---

README.md

Add Faster-Whisper-Transcriber to community integrations.

Add a community integration

---

faster_whisper/transcribe.py

Same as https://github.com/openai/whisper/pull/2005

Prevent infinite loop for out-of-bound timestamps in clip_timestamps

---

faster_whisper/transcribe.py

Removes the wishful heuristic which is causing more issues than it's fixing.
Same as https://github.com/openai/whisper/pull/2043
Example of the issue: https://github.com/openai/whisper/pull/1838#issuecomment-1960041500

Fix window end heuristic for hallucination_silence_threshold

---

faster_whisper/transcribe.py

Related to https://github.com/SYSTRAN/faster-whisper/issues/893 and https://github.com/SYSTRAN/faster-whisper/issues/889

Fix language detection with non-speech audio

---

faster_whisper/transcribe.py

Make vad-related parameters configurable for batched inference.

---

faster_whisper/transcribe.py
faster_whisper/utils.py

This feature allows to specify which revision of the model do you want to download & use

feat: allow passing specific revision to download
